# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 206219acd3e67bcbfb6ec89aa9c5d2e4770a5d0f61bbf746f188118e437768b864ce9cb402d5f2fbd2d40b58e89bc4428ea3a429a6900b0ee80c12780ed17f17

test:
  secret_key_base: 36fb737050d17cff0b8cc5f552981ccb069aa713602311243b613c785d3f23fa0c0f73e04a5469a30ad794471d3f06454f31365d2d528b96d427a3b36d5f5dfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
